# server
server.port=${PORT}

# app
spring.application.name=travelblog
app.cors.allowed_origins=${UI_URL}

#jwt
token.signing.key=${JWT_KEY}

# logging
logging.level.web=${LOG_LEVEL}
logging.level.org.springframework.web=${LOG_LEVEL}
logging.level.org.springframework.security=${LOG_LEVEL}
logging.level.org.hibernate=${LOG_LEVEL}
logging.level.org.hibernate.SQL=${LOG_LEVEL}
logging.level.org.hibernate.type=${LOG_LEVEL}

# jpa

# datasource
spring.datasource.url=jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?useSSL=${DB_SSL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# liquibase
spring.liquibase.change-log=./db/changelog/changelog.json
spring.liquibase.url=jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?useSSL=${DB_SSL}
spring.liquibase.user=${DB_USERNAME}
spring.liquibase.password=${DB_PASSWORD}
